const { Schema, model } = require("mongoose");

const schema = new Schema({
  status: Boolean,
  number: String,
  ticket_code: String,
  start_code: String,
  des_code: String,
  time: String,
  start: String,
  des: String,
  train: String,
  start_day: String,
  start_month: String,
  booking_code: String,
  start_year: String,
  ticket_day: String,
  ticket_month: String,
  ticket_year: String,
  wagon: String,
  chair: String,
  type_code: String,
  name: String,
  price_number: String,
  paper: String,
  price_char: String,
  mst: String,
  origin_price: String,
  name_organization: String,
  tax: String,
  address: String,
  phone: String,
  create_date: {
    type: Date,
    default: Date.now,
  },
  type_code: String,
  type: String,
  name: String,
  price_number: String,
  address: String,
  phone: String,
  id: String,
  number: String,
  sequence: Number,
});

module.exports = model("bill", schema);
